version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: monthly
    reviewers:
      - andyundso
      
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
    reviewers:
      - andyundso
      
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    reviewers:
      - andyundso
