name: Rails
on: push

jobs:
  verify:
    name: Build
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: rails_github_actions
          POSTGRES_DB: rails_github_actions_test
          POSTGRES_PASSWORD: postgres
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          sudo apt-get -yqq install libpq-dev build-essential libcurl4-openssl-dev
      - name: Set up Cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Setup test database
        env:
          DATABASE_URL: postgres://rails_github_actions:postgres@127.0.0.1/anno1800_goods_tracker_test
          RAILS_ENV: test
        run: |
          bundle exec rake db:create db:migrate
      - name: Run tests
        env:
          DATABASE_URL: postgres://rails_github_actions:postgres@127.0.0.1/anno1800_goods_tracker_test
          RAILS_ENV: test
        run: bundle exec rails test:all
